/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "oel-remake-client"

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}